export const defaultThemes = {
    "BACKGROUND_BASE_TITLE": "#272221",
    "BACKGROUND_BASE_SUBTITLE": "#403937",
    "BACKGROUND_BASE_TEXT": "#574F4D",
    "BACKGROUND_BASE_LABEL": "#8D8686",
    "BACKGROUND_BASE_HOVER": "#D7D5D5",
    "BACKGROUND_BASE_BUTTON": "#E6E5E5",
    "BACKGROUND_BASE_INPUT": "#EDEDED",
    "BACKGROUND_BASE_CARD": "#F3F2F2",
    "BACKGROUND_BASE": "#FAFAFA",

    "YELLOW_DARK": "#C47F17",
    "YELLOW_LIGHT": "#F1E9C9",

    "PURPLE_DARK": "#4B2995",
    "PURPLE_LIGHT": "#EBE5F9",

    "YELLOW": "#DBAC2C",
    "WHITE": "#FFFFFF",
    "PURPLE": "#8047F8"
}